
[sncast.devnet]
url = "http://127.0.0.1:5050/"
account = "account-1"
accounts-file = "/Users/sdpbhandari/.starknet_accounts/starknet_open_zeppelin_accounts.json"

[sncast.default]
account = "sepolia"
